name: Test Google Drive Upload

on:
  workflow_dispatch:

jobs:
  test_upload:
    runs-on: ubuntu-latest
    steps:
      - name: Create test file
        run: echo "This is a test file for Google Drive upload" > test.txt

      - name: Upload test file to Google Drive
        uses: logickoder/google-drive-upload@main
        with:
          credentials: ${{ secrets.GCP_CREDENTIAL }} # Add your Google Drive API credentials
          filename: "test.txt"  # Name of the file to upload
          folderID: ${{ secrets.DRIVE_FOLDER_ID }} # ID of the folder in Google Drive where you want to upload the file
          overwrite: "true"
