name: Build Google-Drive-CI-CD

on:
  workflow_dispatch:
    inputs:
      google_drive:
        description: 'Upload apk to google drive'
        required: false
        type: boolean

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  development:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List files for debugging
        run: |
          echo "Current directory structure:"
          find .

      - name: Upload apk to Google Drive
        uses: logickoder/google-drive-upload@main
        with:
          credentials: ${{ secrets.GCP_CREDENTIAL }}
          filename: "./app.py " # Adjust this if find command shows a different path
          folderID: ${{ secrets.DRIVE_FOLDER_ID }}
          overwrite: "true"
